id: P50AD1592
initial_creation_type: input
source_metadata:
  title: Tra Gelong Tsultrim Dargye
  language: bo
  description: 'Texts by the famous Tra Gelong Tsultrim Dargye (khra dge slong tshul
    khrims dar rgyas, 1866–1937) of Golok:'
  volume:
    7fff016580a64fc18f64cb087228fed7:
      title: Words Spoken at the Moment of Passing
      parent: Testament
created_at: '2022-03-01T01:49:08.342316'
last_modified_at: '2022-03-01T01:49:08.342319'
